### ISSUE TITLE
[AirQuality] Add support for maps

### ISSUE THREAD

**Issue by metbril** [kubawolanin/openhab2-addons#1]
Haven't given it much thought but it would be great if it was possible to be able to easily use the [maps](http://aqicn.org/faq/2015-09-18/map-web-service-real-time-air-quality-tile-api/) in a sitemap with a [webview element](https://github.com/openhab/openhab1-addons/wiki/Explanation-of-Sitemaps#element-webview).

If not feasible, I could hack something together as a static HTML page myself (and write a tutorial).

**Comment by kubawolanin** [comment]
@rtvb I like it! In the JSON data there's `geo` attribute with the station's location
```
city: {
name: "Aleja Krasińskiego, Kraków, Małopolska",
url: "http://aqicn.org/city/poland/malopolska/krakow/aleja-krasinskiego/",
geo: [
"50.057678",
"19.926189"
]
},
```

It would be great if you could write a tutorial or at least webview element we could utilize in the binding.
We could create another Channel, let's say, that would contain the URL of the embeddable map? 

Cheers!

**Comment by kubawolanin** [comment]
@rtvb any ideas how to approach this?
I'm keen to include your solution/use case scenario in the `README.md`

**Comment by kubawolanin** [comment]
Regarding [my previous comment](https://github.com/kubawolanin/openhab2-addons/issues/1#issuecomment-274322429) - I've added a `stationLocation` channel that returns coordinates of the station in the following format:
`50.264611, 18.975028`

**Comment by kubawolanin** [comment]
Closing the issue - for now on the `stationLocation` channel is being handled as a `Location` type (instead of `String`) - the UI (e.g. PaperUI) should now display it on a map! :)
