### ISSUE TITLE
[AirQuality] Error for O3 level with decimals

### ISSUE THREAD

**Issue by metbril** [kubawolanin/openhab2-addons#6]
O3 level reports value in decimals (e.g. '4.9').

When I specify an item without specific formatting

```
Number Aqi_O3   "O\u2083 niveau"   <line> (AirQuality) { channel="airquality:aqi:home:o3" }
```

then the binding raises an error:

```
07:50:36.068 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Exception while formatting value '4.9' of item Aqi_O3 with format '%d': java.util.IllegalFormatConversionException: d != java.math.BigDecimal
```

I need to explicitly specify number formatting to the label of the item:

```
Number Aqi_O3   "O\u2083 niveau [%.2f]"   <line> (AirQuality) { channel="airquality:aqi:home:o3" }
```

The binding should gracefully show values even if no number formatting in labels is specified.

**Comment by kubawolanin** [comment]
Thanks for reporting!
I forgot to update the default format of O2 in `thing-types.xml` along with the other ones.
Should be working now :)
