### ISSUE TITLE
AirQuality: add channels for last query

### ISSUE THREAD

**Issue by metbril** [kubawolanin/openhab2-addons#7]
Suggestion:

Add 2 extra channels:
- lastQueryTime, time stamp for last call to API (DateTime)
- lastQueryResult, http result e.g. 200, 404 etc. (Number)

**Comment by kubawolanin** [comment]
I think this is a good candidate for rule.

airquality.items
```
DateTime Aqi_QueryTime "[%1$tm/%1$td %1$tH:%1$tM]"
```

airquality.rules:
```
import org.openhab.core.library.types.*

rule "Last AirQuality query time"
when
  Item Aqi_Description received update
then
  Aqi_QueryTime.postUpdate( new DateTimeType() )
end
```
