### ISSUE TITLE
AirQuality: suppress warning for CO channel

### ISSUE THREAD

**Issue by metbril** [kubawolanin/openhab2-addons#8]
With every query to the API the binding logs a warning that the CO measurement is not available for the station. Since this is no one time event, I would suppress that warning, to prevent flooding the logs with messages that actually do not provide any useful information. Just returning a NULL or UNDEF value to the channel itself will do. The warning message could of course be changed to a debug message.

**Comment by kubawolanin** [comment]
Done. Thank you!
